install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
install.packages("devtools")
install.pacakages("reshape2")
devtools::install_github("uqrmaie1/admixtools")
